- name: variable from files
  hosts: localhost
  vars_files:
  - vars.yaml
  tasks:
  - name: print  override infromation
    ansible.builtin.debug:
      msg: "Hi, we are learning {{course}} from trainer {{trainer}}, duration is {{duration}}"


       
    