- name: variables from file
  hosts: localhost
  tasks:
  - name: print infromation
    ansible.builtin.debug:
      msg: "Hi,we are learnig {{course}} from trainer {{trainer}} duration is {{duration}}"
