- name: varibales preference
  hosts: localhost
  # vars:
  #   wishes: "Morning from PLAY variables"
  vars_files:
  - vars.yaml
  # vars_prompt:
  # - name: wishes
  #   prompt: please enter wishes
  #   private: false

  tasks:
  - name: check preference
    # vars:
    #   wishes: "Morningfrom TASK variables"
    ansible.builtin.debug:
      msg: "hello, Good {{wishes}}"

      # 1.Arguments
      # 2.task veriables
      # 3.variables files
      # 4.prompt
      # 5.play level
      # 6.Inventory
      # 7.Role level