- name: data types
  hosts: localhost
  vars:
    course: devops with AWS # string
    tools: # list
    - linux
    - shell
    - ansible
    Experience: #map or dictionary
      devops: 3 # numbers
      aws: 2
      ansible: 1
    realproject: true #boolean
  tasks:
  - name: print varibales
    ansible.builtin.debug:
      msg: "course:{{course}}, tools covered:{{tools}}, expereince is:{{Experience}} is realproject is {{realproject}}"
