- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "hello {{course | default('ansible') }}"

- name: upper case
  hosts: localhost
  vars:
    greeting: "Hello, good morning"
  tasks:
  - name: converting upper case
    ansible.builtin.debug:
      msg: "{{greeting | upper }}"

- name: lower case
  hosts: localhost
  vars:
    greeting: "HELLO,ALEEF BASHA GOOD MORNING, How are You"
  tasks:
  - name: converting lower case
    ansible.builtin.debug:
      msg: "{{greeting | lower }}"
