- name: install pakages
  hosts: web
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: latest
    loop:
    - mysql
    - nginx
    - postfix